[package]
name = "secure_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
awc = "3.3.0"
url = "2.5.0"
toml = "0.8.8"
colored = "2.1.0"
tracing = "0.1.40"
actix-web = "4.4.1"
macros-rs = "0.5.2"
termcolor = "1.4.1"
tokio-util = "0.7.10"
futures-util = "0.3.30"
tracing-subscriber = "0.3.18"
tracing-bunyan-formatter = "0.3.9"

tokio = { version = "1.35.1", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
pickledb = { version = "0.5.1", features = ["bincode"] }
reqwest = { version = "0.11.23", default-features = false, features = ["stream"] }
