[package]
name = "secure_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.5.0"
toml = "0.8.8"
tera = "1.19.1"
colored = "2.1.0"
tracing = "0.1.40"
actix-web = "4.4.1"
macros-rs = "0.5.2"
termcolor = "1.4.1"
once_cell = "1.19.0"
tokio-util = "0.7.10"
mime_guess = "2.0.4"
futures-util = "0.3.30"
tracing-subscriber = "0.3.18"
actix-web-static-files = "4.0.1"
tracing-bunyan-formatter = "0.3.9"

tokio = { version = "1.35.1", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
awc = { version = "3.3.0", features = ["rustls-0_21"] }
pickledb = { version = "0.5.1", features = ["bincode"] }
include_dir = { version = "0.7.3", features = ["metadata"] }
reqwest = { version = "0.11.23", default-features = false, features = ["stream", "rustls-tls"] }
