[project]
name = "zerotrust"
version = "0.3.0"

[tasks]
clean = { script = ["rm -rf bin", "mkdir bin"] }
assets = { path = "src/pages", script = ["pnpm i", "pnpm build"] }
run = { script = ["maid build -q", "bash -c 'bin/zerotrust | bunyan'"] }

[tasks.build]
depends = ["clean"]
script = [
   "maid assets -q",
   "cargo zigbuild --release", 
   "cp target/release/zerotrust bin/zerotrust"
]

[tasks.build.cache]
path = "src"
target = ["bin/zerotrust"]

[tasks.install]
script = [
   "maid build -q", 
   "sudo cp bin/zerotrust /usr/local/bin",
   "echo Copied binary!"
]